home:
  path: "/"
  display_name: "Home"
new_user:
  path: "/user/new"
  display_name: "New User"
new_book:
  path: "/donate"
  display_name: "New Book"
issued_books:
  path: "/issued-books"
  display_name: "Issued Books"
