home:
  path: "/"
  display_name: "Home"
all_users:
  path: "/users"
  display_name: "Users"
new_book:
  path: "/donate"
  display_name: "New Book"
issued_books:
  path: "/issued-books"
  display_name: "Issued Books"
all_books:
  path: "/books"
  display_name: "All Books"
